#include "metadata.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <stdint.h>
#define TAG_BUDGET (256*1024)
static uint32_t be32(const uint8_t *b){return (uint32_t)b[0]<<24|(uint32_t)b[1]<<16|(uint32_t)b[2]<<8|b[3];}
static uint32_t le32(const uint8_t *b){return (uint32_t)b[3]<<24|(uint32_t)b[2]<<16|(uint32_t)b[1]<<8|b[0];}
static uint32_t sync32(const uint8_t *b){return (b[0]&127)<<21|(b[1]&127)<<14|(b[2]&127)<<7|(b[3]&127);}
long pearl_audio_offset(FILE *f){uint8_t h[10];rewind(f);if(fread(h,1,10,f)!=10||memcmp(h,"ID3",3)||h[3]<2||h[3]>4){rewind(f);return 0;}for(int i=6;i<10;i++)if(h[i]&128){rewind(f);return 0;}long offset=10+sync32(h+6)+((h[3]==4&&(h[5]&16))?10:0);if(fseek(f,0,SEEK_END)||offset>ftell(f)){rewind(f);return 0;}fseek(f,offset,SEEK_SET);return offset;}
static void put_utf8(char *out,size_t *used,uint32_t cp){uint8_t b[4];unsigned n=0;if(cp<128)b[n++]=cp;else if(cp<2048){b[n++]=0xc0|(cp>>6);b[n++]=0x80|(cp&63);}else if(cp<65536){b[n++]=0xe0|(cp>>12);b[n++]=0x80|((cp>>6)&63);b[n++]=0x80|(cp&63);}else{b[n++]=0xf0|(cp>>18);b[n++]=0x80|((cp>>12)&63);b[n++]=0x80|((cp>>6)&63);b[n++]=0x80|(cp&63);}if(*used+n<PEARL_NAME){memcpy(out+*used,b,n);*used+=n;out[*used]=0;}}
static void text(char *out,const uint8_t *p,size_t n){if(!n)return;uint8_t enc=*p++;n--;size_t used=0;out[0]=0;
 if(enc==3){size_t size=n<PEARL_NAME-1?n:PEARL_NAME-1;memcpy(out,p,size);out[size]=0;return;}
 if(enc==0){for(size_t i=0;i<n&&p[i];i++)put_utf8(out,&used,p[i]);return;}
 bool little=false;if(enc==1&&n>=2){little=p[0]==0xff&&p[1]==0xfe;if((p[0]==0xff&&p[1]==0xfe)||(p[0]==0xfe&&p[1]==0xff)){p+=2;n-=2;}}
 if(enc!=1&&enc!=2)return;
 for(size_t i=0;i+1<n;i+=2){uint32_t cp=little?(p[i]|p[i+1]<<8):(p[i]<<8|p[i+1]);if(!cp)break;if(cp>=0xd800&&cp<=0xdbff&&i+3<n){uint32_t lo=little?(p[i+2]|p[i+3]<<8):(p[i+2]<<8|p[i+3]);if(lo>=0xdc00&&lo<=0xdfff){cp=0x10000+((cp-0xd800)<<10)+lo-0xdc00;i+=2;}else cp=0xfffd;}put_utf8(out,&used,cp);}
}
static void assign(pearl_tags *t,const char *key,const char *value){if(!value[0])return;char *dest=NULL;if(!strcasecmp(key,"TITLE"))dest=t->title;else if(!strcasecmp(key,"ARTIST"))dest=t->artist;else if(!strcasecmp(key,"ALBUM"))dest=t->album;else if(!strcasecmp(key,"ALBUMARTIST")||!strcasecmp(key,"ALBUM ARTIST"))dest=t->album_artist;else if(!strcasecmp(key,"TRACKNUMBER"))t->track=strtoul(value,NULL,10);else if(!strcasecmp(key,"DISCNUMBER"))t->disc=strtoul(value,NULL,10);if(dest)snprintf(dest,PEARL_NAME,"%s",value);}
static void comments(pearl_tags *t,const uint8_t *b,size_t n){size_t at=0;if(n<8)return;uint32_t vendor=le32(b);at=4;if(vendor>n-at)return;at+=vendor;if(n-at<4)return;uint32_t count=le32(b+at);at+=4;while(count--&&n-at>=4){uint32_t length=le32(b+at);at+=4;if(length>n-at)return;const uint8_t *eq=memchr(b+at,'=',length);if(eq){size_t keylen=eq-(b+at);if(keylen<64){char key[64],value[PEARL_NAME];memcpy(key,b+at,keylen);key[keylen]=0;size_t val=length-keylen-1;if(val>=sizeof(value))val=sizeof(value)-1;memcpy(value,eq+1,val);value[val]=0;assign(t,key,value);}}at+=length;}}
static void large_id3(FILE *f,pearl_tags *t,unsigned version,uint32_t size,uint8_t flags){if(flags&128)return;if(flags&64){uint8_t ext[4];if(size<4||fread(ext,1,4,f)!=4)return;uint32_t n=version==4?sync32(ext):be32(ext)+4;if(n<4||n>size)return;fseek(f,n-4,SEEK_CUR);size-=n;}while(size>=10){uint8_t h[10];if(fread(h,1,10,f)!=10||!h[0])return;size-=10;uint32_t n=version==4?sync32(h+4):be32(h+4);if(n>size)return;size-=n;const char *key=NULL;if(!memcmp(h,"TIT2",4))key="TITLE";else if(!memcmp(h,"TPE1",4))key="ARTIST";else if(!memcmp(h,"TPE2",4))key="ALBUMARTIST";else if(!memcmp(h,"TALB",4))key="ALBUM";else if(!memcmp(h,"TRCK",4))key="TRACKNUMBER";else if(!memcmp(h,"TPOS",4))key="DISCNUMBER";if(key&&n<=4096&&h[8]==0&&h[9]==0){uint8_t data[4096];char value[PEARL_NAME]={0};if(fread(data,1,n,f)!=n)return;text(value,data,n);assign(t,key,value);}else if(fseek(f,n,SEEK_CUR))return;}}
static void ogg_comments(FILE *f,pearl_tags *t){uint8_t *packet=NULL;size_t used=0;unsigned pages=0;while(pages++<128){uint8_t h[27],segments[255];if(fread(h,1,27,f)!=27||memcmp(h,"OggS",4))break;unsigned count=h[26];if(fread(segments,1,count,f)!=count)break;bool failed=false;for(unsigned i=0;i<count;i++){unsigned n=segments[i];if(used+n>TAG_BUDGET){failed=true;break;}uint8_t *next=realloc(packet,used+n+1);if(!next){failed=true;break;}packet=next;if(fread(packet+used,1,n,f)!=n){failed=true;break;}used+=n;if(n<255){if(used>=4&&(packet[0]&127)==4){uint32_t length=(uint32_t)packet[1]<<16|packet[2]<<8|packet[3];if(length<=used-4)comments(t,packet+4,length);free(packet);return;}used=0;}}if(failed)break;}free(packet);}
static void wave_info(FILE *f,pearl_tags *t){fseek(f,12,SEEK_SET);uint8_t h[8];for(unsigned chunks=0;chunks<4096&&fread(h,1,8,f)==8;chunks++){uint32_t n=le32(h+4);if(!memcmp(h,"LIST",4)&&n<=TAG_BUDGET&&n>=4){uint8_t *b=malloc(n);if(!b)return;if(fread(b,1,n,f)!=n){free(b);return;}if(!memcmp(b,"INFO",4)){size_t at=4;while(n-at>=8){uint32_t size=le32(b+at+4);const char *key=NULL;if(!memcmp(b+at,"INAM",4))key="TITLE";else if(!memcmp(b+at,"IART",4))key="ARTIST";else if(!memcmp(b+at,"IPRD",4))key="ALBUM";else if(!memcmp(b+at,"ITRK",4))key="TRACKNUMBER";at+=8;if(size>n-at)break;if(key){uint8_t data[PEARL_NAME+1]={0};size_t bytes=size<PEARL_NAME?size:PEARL_NAME;memcpy(data+1,b+at,bytes);char value[PEARL_NAME]={0};text(value,data,bytes+1);assign(t,key,value);}at+=size;if(size&1){if(at==n)break;at++;}}}free(b);if(n&1)fseek(f,1,SEEK_CUR);}else if(fseek(f,(long)n+(n&1),SEEK_CUR))break;}}
void pearl_metadata(const char *path,pearl_tags *t){memset(t,0,sizeof(*t));FILE *f=fopen(path,"rb");if(!f)return;uint8_t h[10];if(fread(h,1,10,f)!=10)goto end;
 if(!memcmp(h,"ID3",3)&&(h[3]==2||h[3]==3||h[3]==4)){
  unsigned version=h[3];uint32_t size=sync32(h+6);if(size>TAG_BUDGET){if(version!=2)large_id3(f,t,version,size,h[5]);goto native;}uint8_t *b=malloc(size);if(!b)goto end;if(fread(b,1,size,f)!=size){free(b);goto end;}if(h[5]&128){size_t out=0;for(size_t i=0;i<size;i++){b[out++]=b[i];if(b[i]==255&&i+1<size&&b[i+1]==0)i++;}size=out;}
  size_t at=0;if(version!=2&&(h[5]&64)){if(size<4){free(b);goto end;}uint32_t ext=version==4?sync32(b):be32(b)+4;if(ext>size){free(b);goto end;}at=ext;}
  while(size-at>=(version==2?6u:10u)&&b[at]){uint8_t *frame=b+at;uint32_t len=version==2?((uint32_t)frame[3]<<16|frame[4]<<8|frame[5]):version==4?sync32(frame+4):be32(frame+4);at+=version==2?6:10;if(len>size-at)break;const char *key=NULL;if(!memcmp(frame,"TIT2",4))key="TITLE";else if(!memcmp(frame,"TPE1",4))key="ARTIST";else if(!memcmp(frame,"TPE2",4))key="ALBUMARTIST";else if(!memcmp(frame,"TALB",4))key="ALBUM";else if(!memcmp(frame,"TRCK",4))key="TRACKNUMBER";else if(!memcmp(frame,"TPOS",4))key="DISCNUMBER";if(version==2){if(!memcmp(frame,"TT2",3))key="TITLE";else if(!memcmp(frame,"TP1",3))key="ARTIST";else if(!memcmp(frame,"TP2",3))key="ALBUMARTIST";else if(!memcmp(frame,"TAL",3))key="ALBUM";else if(!memcmp(frame,"TRK",3))key="TRACKNUMBER";else if(!memcmp(frame,"TPA",3))key="DISCNUMBER";}if(key&&(version==2||!(frame[9]&(version==4?0x4f:0xe0)))){char value[PEARL_NAME]={0};text(value,b+at,len);assign(t,key,value);}at+=len;}free(b);
 }
native:;
 long offset=pearl_audio_offset(f);fseek(f,offset,SEEK_SET);if(fread(h,1,4,f)==4&&!memcmp(h,"fLaC",4)){size_t budget=0;while(fread(h,1,4,f)==4){uint32_t n=(uint32_t)h[1]<<16|h[2]<<8|h[3];if((h[0]&127)==4&&n<=TAG_BUDGET&&budget+n<=TAG_BUDGET){uint8_t *b=malloc(n);if(!b)break;if(fread(b,1,n,f)==n)comments(t,b,n);free(b);budget+=n;}else if(fseek(f,n,SEEK_CUR))break;if(h[0]&128)break;}}
else if(!memcmp(h,"RIFF",4)){wave_info(f,t);}
 else if(!memcmp(h,"OggS",4)){fseek(f,offset,SEEK_SET);ogg_comments(f,t);}
end:;
 if(!t->title[0]||!t->artist[0]||!t->album[0]){uint8_t v1[128];if(!fseek(f,-128,SEEK_END)&&fread(v1,1,128,f)==128&&!memcmp(v1,"TAG",3)){char *fields[]={t->title,t->artist,t->album};for(int i=0;i<3;i++)if(!fields[i][0]){uint8_t value[31]={0};memcpy(value+1,v1+3+i*30,30);text(fields[i],value,sizeof(value));size_t n=strlen(fields[i]);while(n&&fields[i][n-1]==' ')fields[i][--n]=0;}if(!t->track&&v1[125]==0)t->track=v1[126];}}
 fclose(f);}
