#include "playlist.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <ctype.h>
#define PLAYLIST_LIMIT (1024*1024)
static int hex(char c){if(c>='0'&&c<='9')return c-'0';c=tolower((unsigned char)c);return c>='a'&&c<='f'?c-'a'+10:-1;}
static bool decode(char *out,const char *s,size_t n,bool uri){size_t used=0;for(size_t i=0;i<n&&used<PEARL_PATH-1;i++){unsigned char ch=s[i];if(uri&&ch=='%'&&i+2<n){int a=hex(s[i+1]),b=hex(s[i+2]);if(a<0||b<0)return false;ch=(a<<4)|b;i+=2;}else if(ch=='&'){const char *names[]={"amp;","lt;","gt;","quot;","apos;"};const char chars[]="&<>\"'";bool found=false;for(unsigned j=0;j<5;j++)if(i+1+strlen(names[j])<=n&&!strncmp(s+i+1,names[j],strlen(names[j]))){ch=chars[j];i+=strlen(names[j]);found=true;break;}if(!found&&i+2<n&&s[i+1]=='#'){size_t end=i+2;bool x=s[end]=='x'||s[end]=='X';if(x)end++;size_t begin=end;while(end<n&&s[end]!=';')end++;if(end>=n||end-begin>8||end==begin)return false;char digits[9];memcpy(digits,s+begin,end-begin);digits[end-begin]=0;char *finish;unsigned long cp=strtoul(digits,&finish,x?16:10);if(*finish||!cp||cp>0x10ffff||(cp>=0xd800&&cp<=0xdfff))return false;unsigned char bytes[4];unsigned length;if(cp<128){bytes[0]=cp;length=1;}else if(cp<2048){bytes[0]=0xc0|(cp>>6);bytes[1]=0x80|(cp&63);length=2;}else if(cp<65536){bytes[0]=0xe0|(cp>>12);bytes[1]=0x80|((cp>>6)&63);bytes[2]=0x80|(cp&63);length=3;}else{bytes[0]=0xf0|(cp>>18);bytes[1]=0x80|((cp>>12)&63);bytes[2]=0x80|((cp>>6)&63);bytes[3]=0x80|(cp&63);length=4;}if(used+length>=PEARL_PATH)return false;memcpy(out+used,bytes,length);used+=length;i=end;continue;}if(!found&&uri)return false;}if(!ch||ch=='\r'||ch=='\n')return false;out[used++]=ch;}out[used]=0;return n<PEARL_PATH;}
static char *tag(char *p,const char *name,bool closing,char **content){while((p=strchr(p,'<'))){char *start=p++,*local=p;if(*p=='/'){if(!closing)continue;local=++p;}else if(closing)continue;char *end=p;while(*end&&(isalnum((unsigned char)*end)||*end=='_'||*end=='-'||*end==':'||*end=='.')){if(*end==':')local=end+1;end++;}if((size_t)(end-local)!=strlen(name)||strncmp(local,name,end-local))continue;if(*end!='>'&&!isspace((unsigned char)*end))continue;char *right=strchr(end,'>');if(!right)return NULL;*content=right+1;return start;}return NULL;}
static bool normalize(char *out,const char *base,const char *entry,const char *root){char joined[PEARL_PATH*2];if(!strncmp(entry,"file://",7)){entry+=7;if(!strncmp(entry,"localhost/",10))entry+=9;else if(entry[0]!='/')return false;}if(!strncmp(entry,"/music/",7)){if(snprintf(joined,sizeof(joined),"%s%s",root,entry+6)>=(int)sizeof(joined))return false;entry=joined;}char mapped[PEARL_PATH*2];snprintf(mapped,sizeof(mapped),"%s",entry);entry=mapped;if(strstr(entry,"://")||strchr(entry,':'))return false;if(snprintf(joined,sizeof(joined),"%s%s%s",entry[0]=='/'?"":base,entry[0]=='/'?"":"/",entry)>=(int)sizeof(joined))return false;char *parts[PEARL_PATH/2];unsigned count=0;char *save;for(char *part=strtok_r(joined,"/",&save);part;part=strtok_r(NULL,"/",&save)){if(!strcmp(part,"."))continue;if(!strcmp(part,"..")){if(!count)return false;count--;continue;}if(count==PEARL_PATH/2)return false;parts[count++]=part;}size_t used=0;for(unsigned i=0;i<count;i++){size_t n=strlen(parts[i]);if(used+n+1>=PEARL_PATH)return false;out[used++]='/';memcpy(out+used,parts[i],n);used+=n;}out[used]=0;size_t r=strlen(root);return !strncmp(out,root,r)&&(out[r]=='/'||!out[r]);}
static bool add(pearl_library *l,unsigned collection,const char *base,const char *entry,const char *root){char path[PEARL_PATH];if(!normalize(path,base,entry,root)){l->skipped++;return false;}for(unsigned i=0;i<l->track_count;i++)if(!strcasecmp(path,l->tracks[i].path))return pearl_collection_append(l,collection,i);l->skipped++;return false;}
void pearl_playlist_read(pearl_library *l,unsigned index,const char *root){pearl_collection *c=&l->collections[index];FILE *f=fopen(c->path,"rb");if(!f){l->skipped++;return;}fseek(f,0,SEEK_END);long bytes=ftell(f);rewind(f);if(bytes<0||bytes>PLAYLIST_LIMIT){l->skipped++;fclose(f);return;}char base[PEARL_PATH];snprintf(base,sizeof(base),"%s",c->path);char *slash=strrchr(base,'/');if(slash)*slash=0;const char *ext=strrchr(c->path,'.');
 if(ext&&!strcasecmp(ext,".xspf")){char *xml=malloc(bytes+1);if(!xml){l->truncated=true;fclose(f);return;}if(fread(xml,1,bytes,f)!=(size_t)bytes){free(xml);fclose(f);return;}xml[bytes]=0;if(strstr(xml,"<!DOCTYPE")||strstr(xml,"<!ENTITY")||strstr(xml,"xml:base=")){l->skipped++;free(xml);fclose(f);return;}
 char *p=xml,*start;while(tag(p,"track",false,&start)){char *after,*end=tag(start,"track",true,&after);if(!end)break;char *loc=start,*value;while(tag(loc,"location",false,&value)&&value<end){char *next,*finish=tag(value,"location",true,&next);if(!finish||finish>end)break;char entry[PEARL_PATH];if(decode(entry,value,finish-value,true)&&add(l,index,base,entry,root))break;loc=next;}p=after;}free(xml);
 }else{char line[PEARL_PATH+8];bool first=true;while(fgets(line,sizeof(line),f)){size_t n=strlen(line);if(n==sizeof(line)-1&&line[n-1]!='\n'){int ch;while((ch=fgetc(f))!=EOF&&ch!='\n'){}l->skipped++;continue;}char *entry=line;if(first&&n>=3&&!memcmp(entry,"\xef\xbb\xbf",3))entry+=3;first=false;entry[strcspn(entry,"\r\n")]=0;while(isspace((unsigned char)*entry))entry++;if(!*entry||*entry=='#')continue;add(l,index,base,entry,root);}}
 fclose(f);}
